Pi_network_Market_Niger/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('user.urls')),
    path('shop/', include('shop.urls')),
    path('panier/', include('panier.urls')),
    path('commande/', include('commande.urls')),
    path('', views.search, name='search'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

panier/urls.py
from django.urls import path
from . import views

app_name = 'panier'

urlpatterns = [
    path('cart/', views.cart_detail, name='cart_detail'),
    path('cart/add/<int:article_id>/', views.cart_add, name='cart_add'),
    path('cart/remove/<int:cart_item_id>/', views.cart_remove, name='cart_remove'),
    path('cart/update/<int:cart_item_id>/', views.cart_update, name='cart_update'),
]

shop/urls.py
from django.urls import path
from . import views


app_name = 'shop'

urlpatterns = [
    path('vendor/dashboard/', views.vendor_dashboard, name='vendor_dashboard'),
    path('vendor/create_shop/', views.create_shop, name='create_shop'),
    path('vendor/update_shop/<int:shop_id>/', views.update_shop, name='update_shop'),
    path('vendor/delete_shop/<int:shop_id>/', views.delete_shop, name='delete_shop'),
    path('vendor/create_category/', views.create_category, name='create_category'),
    path('vendor/update_category/<int:category_id>/', views.update_category, name='update_category'),
    path('vendor/delete_category/<int:category_id>/', views.delete_category, name='delete_category'),
    path('vendor/create_article/', views.create_article, name='create_article'),
    path('vendor/update_article/<int:article_id>/', views.update_article, name='update_article'),
    path('vendor/delete_article/<int:article_id>/', views.delete_article, name='delete_article'),
    path('category/<int:category_id>/', views.category_detail, name='category_detail'),
    path('article/<int:article_id>/', views.article_detail, name='article_detail'),
    path('vendeur/<int:pk>/', views.vendeur_detail, name='vendeur_detail'),
    #path('shop/<int:pk>/', views.shop_detail, name='shop_detail'),
    path('shops/', views.shop_list, name='shop_list'),
]

user/urls.py
from django.urls import path
from . import views

app_name = 'user'

urlpatterns = [
    path('login/', views.login_page, name='login'),
    path('logout/', views.deconnexion, name='logout'),
    path('register/', views.register, name='register'),
]

shop/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.urls import reverse
from django.core.exceptions import ValidationError



class Shop(models.Model):
    name = models.CharField(max_length=50, default=None)
    description = models.TextField(default=None)
    user = models.OneToOneField(get_user_model(), on_delete=models.CASCADE)
    image = models.ImageField(
        verbose_name='image',
        upload_to='shop',
        default=None
    )

    def __str__(self):
        return self.name 


class Category(models.Model):
    name = models.CharField(max_length=50, default=None)
    description = models.TextField(max_length=150, default=None)
    shop = models.ForeignKey(Shop, on_delete=models.CASCADE)
    image = models.ImageField(verbose_name='image', upload_to='shop', null=True)

    def __str__(self):
        return self.name


class Article(models.Model):
    name = models.CharField(max_length=50, default=None)
    description = models.TextField(default=None)
    qte = models.IntegerField()
    price = models.DecimalField(max_digits=7, decimal_places=2)
    image = models.ImageField(verbose_name='image', upload_to='shop', null=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    views_count = models.IntegerField(default=0)
    vendeur = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('shop:vendeur_detail', args=[str(self.vendeur.id)])
    
    def clean(self):
        if self.qte <= 0:
            raise ValidationError('La quantité doit être supérieure à zéro.')
        if self.price <= 0:
            raise ValidationError('Le prix doit être supérieur à zéro.')

shop/forms.py
from django import forms
from django.forms import ModelForm
from django.db import models
from .models import Category, Shop, Article
from user.models import User


class ShopForm(ModelForm):
    class Meta:
        model = Shop
        exclude = ('user', 'market')
        #ields = '__all__'


class CategoryForm(ModelForm):
    class Meta:
        model = Category
        exclude = ('shop',)

class ArticleForm(ModelForm):
    class Meta:
        model = Article
        exclude = ('vendeur','views_count')
        
    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user')
        super(ArticleForm, self).__init__(*args, **kwargs)

shop/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.decorators import user_passes_test
from django.http import HttpResponse
from django.core.paginator import Paginator
from django.contrib.auth import get_user_model
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.contrib import messages
import uuid
from .models import Shop, Category, Article
from .forms import ShopForm, CategoryForm, ArticleForm
from django import forms
from user.models import User


@login_required
def vendor_dashboard(request):
    try:
        shop = Shop.objects.get(user=request.user)
    except Shop.DoesNotExist:
        # Rediriger l'utilisateur vers la page de création de boutique
        return redirect('shop:create_shop')

    category_list = Category.objects.filter(shop=shop)
    paginator = Paginator(category_list, 4) # Afficher 10 catégories par page

    page = request.GET.get('page')
    try:
        categories = paginator.page(page)
    except PageNotAnInteger:
        # Si la page n'est pas un entier, afficher la première page
        categories = paginator.page(1)
    except EmptyPage:
        # Si la page est vide, afficher la dernière page
        categories = paginator.page(paginator.num_pages)

    return render(request, 'vendor/dashboard.html', {'shop': shop, 'categories': categories})
    return render(request, 'vendor/dashboard.html', {'shop': shop, 'categories': categories, 'articles': articles})


@login_required
def vendor_articles(request):
    shop = get_object_or_404(Shop, user=request.user)
    articles = Article.objects.filter(category__shop=shop)
    return render(request, 'vendor/articles.html', {'articles': articles})

@login_required
def vendor_categories(request):
    shop = get_object_or_404(Shop, user=request.user)
    categories = Category.objects.filter(shop=shop)
    return render(request, 'vendor/categories.html', {'categories': categories})

@user_passes_test(lambda user: user.is_authenticated and user.fonction == 2)
def create_shop(request):
    if request.method == 'POST':
        form = ShopForm(request.POST, request.FILES)
        if form.is_valid():
            shop = form.save(commit=False)
            shop.user = request.user
            shop.save()
            messages.success(request, 'Shop created successfully.')
            return redirect('shop:vendor_dashboard')
    else:
        form = ShopForm()
    return render(request, 'vendor/create_shop.html', {'form': form})

@user_passes_test(lambda user: user.is_authenticated and user.fonction == 2)
def update_shop(request, shop_id):
    shop = get_object_or_404(Shop, pk=shop_id)
    if request.method == 'POST':
        form = ShopForm(request.POST, request.FILES, instance=shop)
        if form.is_valid():
            form.save()
            messages.success(request, 'Shop updated successfully.')
            return redirect('shop:vendor_dashboard')
    else:
        form = ShopForm(instance=shop)
    return render(request, 'vendor/update_shop.html', {'form': form, 'shop': shop})

@user_passes_test(lambda user: user.is_authenticated and user.fonction == 2)
def delete_shop(request, shop_id):
    shop = get_object_or_404(Shop, pk=shop_id)
    shop.delete()
    messages.success(request, 'Shop deleted successfully.')
    return redirect('shop:vendor_dashboard')

@user_passes_test(lambda user: user.is_authenticated and user.fonction == 2)
def create_category(request):
    shop = get_object_or_404(Shop, user=request.user)
    if request.method == 'POST':
        form = CategoryForm(request.POST, request.FILES)
        if form.is_valid():
            category = form.save(commit=False)
            category.shop = shop
            category.save()
            messages.success(request, 'Category created successfully.')
            return redirect('shop:vendor_dashboard')
    else:
        form = CategoryForm()
    return render(request, 'vendor/create_category.html', {'form': form})

@user_passes_test(lambda user: user.is_authenticated and user.fonction == 2)
def update_category(request, category_id):
    category = get_object_or_404(Category, pk=category_id)
    if request.method == 'POST':
        form = CategoryForm(request.POST, request.FILES, instance=category)
        if form.is_valid():
            form.save()
            messages.success(request, 'Category updated successfully.')
            return redirect('shop:vendor_dashboard')
    else:
        form = CategoryForm(instance=category)
    return render(request, 'vendor/update_category.html', {'form': form, 'category': category})

def category_detail(request, category_id):
    category = get_object_or_404(Category, pk=category_id)
    articles = Article.objects.filter(category=category)
    context = {'category': category, 'articles': articles}
    return render(request, 'category_detail.html', context)

@user_passes_test(lambda user: user.is_authenticated and user.fonction == 2)
def delete_category(request, category_id):
    category = get_object_or_404(Category, pk=category_id)
    category.delete()
    messages.success(request, 'Category deleted successfully.')
    return redirect('shop:vendor_dashboard')

@user_passes_test(lambda user: user.is_authenticated and user.fonction == 2)
def create_article(request):
    shop = get_object_or_404(Shop, user=request.user)
    if request.method == 'POST':
        form = ArticleForm(request.POST, request.FILES, user=request.user)
        if form.is_valid():
            article = form.save(commit=False)
            article.vendeur = request.user
            article.category.shop = shop
            article.save()
            messages.success(request, 'Article created successfully.')
            return redirect('shop:vendor_dashboard')
    else:
        categories = Category.objects.filter(shop=shop)
        form = ArticleForm(user=request.user)
        form.fields['category'].queryset = categories
    return render(request, 'vendor/create_article.html', {'form': form})




@user_passes_test(lambda user: user.is_authenticated and user.fonction == 2)
def update_article(request, article_id):
    shop = get_object_or_404(Shop, user=request.user)
    article = get_object_or_404(Article, pk=article_id, category__shop=shop)
    if request.method == 'POST':
        form = ArticleForm(request.POST, request.FILES, instance=article, user=request.user)

        if form.is_valid():
            form.save()
            
            messages.success(request, 'Article updated successfully.')
            return redirect('shop:vendor_dashboard')
    else:
        #form = ArticleForm(instance=article)
        categories = Category.objects.filter(shop=shop)
        form = ArticleForm(instance=article, user=request.user)
        form.fields['category'].queryset = categories
    return render(request, 'vendor/update_article.html', {'form': form})

def article_detail(request, article_id):
    article = get_object_or_404(Article, pk=article_id)

    # Retrieve the user's ID or generate a random one
    user_id = request.COOKIES.get('user_id')
    if not user_id:
        user_id = str(uuid.uuid4())
        response = HttpResponse()
        response.set_cookie('user_id', user_id)

    # Retrieve the user's views or initialize them to an empty dictionary
    user_views = request.session.get('user_views', {})
    article_views = user_views.get(user_id, {})
    article_view_count = article_views.get(str(article.id), 0)

    # Increment the view count for the article
    if request.user != article.vendeur and user_id != str(article.vendeur.id) and article_view_count == 0:
        article.views_count += 1
        article.save()
        article_views[str(article.id)] = 1
        user_views[user_id] = article_views
        request.session['user_views'] = user_views

    context = {'article': article}
    return render(request, 'article_detail.html', context)

@user_passes_test(lambda user: user.is_authenticated and user.fonction == 2)
def delete_article(request, article_id):
    shop = get_object_or_404(Shop, user=request.user)
    article = get_object_or_404(Article, pk=article_id, category__shop=shop)
    if request.method == 'POST':
        article.delete()
        messages.success(request, 'Article deleted successfully.')
        return redirect('shop:vendor_dashboard')
    return render(request, 'vendor/delete_article.html', {'article': article})


def vendeur_detail(request, pk):
    vendeur = get_object_or_404(User, pk=pk)
    articles = Article.objects.filter(vendeur=vendeur)
    paginator = Paginator(articles, 9)
    page = request.GET.get('page')
    try:
        articles = paginator.page(page)
    except PageNotAnInteger:
        articles = paginator.page(1)
    except EmptyPage:
        articles = paginator.page(paginator.num_pages)
    context = {'vendeur': vendeur, 'articles': articles}
    return render(request, 'vendor/vendeur_detail.html', context)


def shop_list(request):
    shops = Shop.objects.all()
    search_query = request.GET.get('q')
    if search_query:
        shops = shops.filter(name__icontains=search_query)
    paginator = Paginator(shops, 10)  # afficher 10 boutiques par page
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(request, 'shop/shop_list.html', {'page_obj': page_obj, 'search_query': search_query})

shop/templates/article_detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <h1>{{ article.name }}</h1>
                <p>{{ article.description }}</p>
                <p>Price: {{ article.price }}</p>
                <p>Quantity available: {{ article.qte }}</p>
                
                {% if request.user == article.vendeur %}
                    <p>Nombre de vues: {{ article.views_count }}</p>
                {% endif %}
                {% if user.is_authenticated %}
                    <form method="post" action="{% url 'panier:cart_add' article.id %}">
                        {% csrf_token %}
                        <input type="hidden" name="article_id" value="{{ article.id }}">
                        <label for="quantity">Quantity:</label>
                        <input type="number" name="quantity" id="quantity" min="1" value="1">
                        <button type="submit" class="btn btn-primary">Add to Cart</button>
                    </form>
                    
                {% else %}
                    <p>Please <a href="{% url 'user:login' %}?next={{ request.path }}">log in</a> to add items to your cart.</p>
                {% endif %}

            </div>
            <div class="col-md-6">
                {% if user.is_authenticated %}
                    <p>
                        Contacter le vendeur: 
                        <a href="https://wa.me/{{ article.category.shop.user.phone_number }}"> 
                            {{ article.category.shop.user.phone_number }}
                            <img src="{% static 'shop/images/icones_wathsapp.jpg' %}" alt="WhatsApp" style="width: 60px; height: 60px;">
                        </a>
                    </p>
                {% endif %}
                {% if article.image %}
                    <img src="{{ article.image.url }}" alt="{{ article.name }}" class="img-fluid">
                {% else %}
                    <img src="{% static 'images/default-store.jpg' %}" alt="Default Image" class="img-fluid">
                {% endif %}  
            </div>
        </div>
    </div>
{% endblock %}

shop/templates/category_detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="container">
        <h1>{{ category.name }}</h1>
        <p>{{ category.description }}</p>
        {% if category.image %}
            <img src="{{ category.image.url }}" alt="{{ category.name }}" class="img-fluid">
        {% else %}
            <img src="{% static 'images/default-store.jpg' %}" alt="Default Image" class="img-fluid">
        {% endif %}
        <hr>
        <h2>Articles in this category:</h2>
        <div class="row">
            {% for article in articles %}
                <div class="col-md-4 mb-4">
                    <div class="card">
                        {% if article.image %}
                            <img src="{{ article.image.url }}" class="card-img-top" alt="{{ article.name }}">
                        {% else %}
                            <img src="{% static 'images/default-store.jpg' %}" class="card-img-top" alt="Default Image">
                        {% endif %}
                        <div class="card-body">
                            <h5 class="card-title">{{ article.name }}</h5>
                            <p class="card-text">{{ article.description }}</p>
                            <a href="{% url 'shop:article_detail' article.id %}" class="btn btn-primary">Detail</a>
                            {% if user.is_authenticated and user == article.vendeur %}
                                <a href="{% url 'shop:update_article' article.id %}" class="btn btn-outline-secondary">Modifier</a>
                                <a href="{% url 'shop:delete_article' article.id %}" class="btn btn-outline-danger">Supprimer</a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            {% empty %}
                <p>No articles in this category yet.</p>
            {% endfor %}
        </div>
    </div>
{% endblock %}

shop/templates/dashboard.html
{% extends "base.html" %}

{% block body %}
    <div class="container-fluid m-2 h-25" >
        <div class="row">
            
            <div class="col-sm col-10 border border-success">
                {% block entete %} 
                   
                {% endblock %}
            </div>
            <div class="col-sm border border-warning">
                {% block profile %} 
                    {% include "profile.html" %}
                {% endblock %}
            </div>
        </div>
    </div>

    <div class="row container-fluid border border-dark ">
        <div class="col-sm col-2 border border-success ">
            <div class="list-group">
                {% block menue %} 
                    <a href="{% url 'newshop' %}" class="list-group-item list-group-item-action"> Update Shop</a>
                    <a href="{% url 'mesboutique' %}" class="list-group-item list-group-item-action"> Mes boutiques</a>
                    <a href="#" class="list-group-item list-group-item-action"> Categories</a>
                    <a href="#" class="list-group-item list-group-item-action"> Voir les Categories</a>
                    {% comment %} <a href="#" class="list-group-item list-group-item-action">Produits</a>
                    <a href="#" class="list-group-item list-group-item-action">statistiques</a> {% endcomment %}
                {% endblock %}
            </div>
        </div>

        <div class="col-sm col-10 border border-dark">
            {% block content %} Inserer le corps du menu {% endblock %}
        </div>  
    </div>

{% endblock %}

shop/templates/mesboutique.html
{% extends "dashboard.html" %}


{% block content %}
<div class="container">
    <table class="table table-hover">
        <thead>
        <tr>
            <th>Nom de la boutique</th>
            <th>Description</th>
            <th>Couvertures</th>
            <th>Update</th>
            <th>Delette</th>
        </tr>
        </thead>
        <tbody>
            {% load static %}
            {% for p in page_obj %}
                <tr>
                    <td>{{p.name}}</td>
                    <td>{{p.description}}</td>
                    <td>
                        <a href="#" class="list-group-item list-group-item-action">
                            {% comment %} {% if user.avatar != "" %}
                                <img src="{{ p.image.url }}"/>
                            {% endif %} {% endcomment %}
                            <img src="{{ p.image.url }}"/>
                        </a>
                    </td>
                   
                    <td>
                        <a href="#" class="list-group-item list-group-item-action">
                            <img src="{% static 'images/update.png' %}" alt="update" title="pdate"/>
                        </a>
                    </td>
                    <td>
                        <a href="#" class="list-group-item list-group-item-action">
                            <img src="{% static 'images/delette.png' %}"/>
                        </a>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>


<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>
{% endblock %}

shop/templates/newshop.html
{% extends "dashboard.html" %}

{% load bootstrap5 %}
{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript %}
{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}

{% block content %}
    <form enctype="multipart/form-data" action="{% url 'newshop' %}" method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            <button type="submit" class="btn btn-primary">
                Enregister
            </button>
        {% endbuttons %}
    </form>
{% endblock %}