Pi_network_Market_Niger/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('user.urls')),
    path('shop/', include('shop.urls')),
    path('panier/', include('panier.urls')),
    path('commande/', include('commande.urls')),
    path('', views.search, name='search'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

commande/urls.py
from django.urls import path
from . import views

app_name = 'commande'

urlpatterns = [
    path('order_confirmation/', views.order_confirmation, name='order_confirmation'),
    path('order_detail/<int:order_id>/', views.order_detail, name='order_detail'),
    path('order_cancel/<int:order_id>/', views.order_cancel, name='order_cancel'),
    path('order_confirm/<int:order_id>/', views.order_confirm, name='order_confirm'),
    path('order_ship/<int:order_id>/', views.order_ship, name='order_ship'),
    path('order_deliver/<int:order_id>/', views.order_deliver, name='order_deliver'),
    path('order_create/', views.order_create, name='order_create'),
    path('history/', views.order_history, name='order_history'),
    path('tracking/<int:order_id>/', views.order_tracking, name='order_tracking'),
    path('dashboard/', views.dashboard, name='dashboard'),
]
 

panier/urls.py
from django.urls import path
from . import views

app_name = 'panier'

urlpatterns = [
    path('cart/', views.cart_detail, name='cart_detail'),
    path('cart/add/<int:article_id>/', views.cart_add, name='cart_add'),
    path('cart/remove/<int:cart_item_id>/', views.cart_remove, name='cart_remove'),
    path('cart/update/<int:cart_item_id>/', views.cart_update, name='cart_update'),
]

shop/urls.py
from django.urls import path
from . import views


app_name = 'shop'

urlpatterns = [
    path('vendor/dashboard/', views.vendor_dashboard, name='vendor_dashboard'),
    path('vendor/create_shop/', views.create_shop, name='create_shop'),
    path('vendor/update_shop/<int:shop_id>/', views.update_shop, name='update_shop'),
    path('vendor/delete_shop/<int:shop_id>/', views.delete_shop, name='delete_shop'),
    path('vendor/create_category/', views.create_category, name='create_category'),
    path('vendor/update_category/<int:category_id>/', views.update_category, name='update_category'),
    path('vendor/delete_category/<int:category_id>/', views.delete_category, name='delete_category'),
    path('vendor/create_article/', views.create_article, name='create_article'),
    path('vendor/update_article/<int:article_id>/', views.update_article, name='update_article'),
    path('vendor/delete_article/<int:article_id>/', views.delete_article, name='delete_article'),
    path('category/<int:category_id>/', views.category_detail, name='category_detail'),
    path('article/<int:article_id>/', views.article_detail, name='article_detail'),
    path('vendeur/<int:pk>/', views.vendeur_detail, name='vendeur_detail'),
    #path('shop/<int:pk>/', views.shop_detail, name='shop_detail'),
    path('shops/', views.shop_list, name='shop_list'),
]

user/urls.py
from django.urls import path
from . import views

app_name = 'user'

urlpatterns = [
    path('login/', views.login_page, name='login'),
    path('logout/', views.deconnexion, name='logout'),
    path('register/', views.register, name='register'),
]

Pi_network_Market_Niger/forms.py
from django import forms

class searchForm(forms.Form):
    search = forms.CharField(widget=forms.TextInput(
                                attrs={
                                    'size': '120'
                                    }
                                ))

Pi_network_Market_Niger/views.py
from django.core.paginator import Paginator
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import render
from shop.models import Article
from django.db.models import Count
from django.db.models import F


def search(request):
    query = request.GET.get('q')
    if query:
        articles = Article.objects.filter(name__icontains=query)
    else:
        articles = Article.objects.none()  # retourner une queryset vide si q est None

    # Ajouter la pagination
    paginator = Paginator(articles, 10)
    page = request.GET.get('page')
    try:
        results = paginator.page(page)
    except PageNotAnInteger:
        results = paginator.page(1)
    except EmptyPage:
        results = paginator.page(paginator.num_pages)

    # Récupérer les 5 articles les plus consultés
    top_articles = Article.objects.order_by('-views_count')[:5]

    context = {'articles': results, 'query': query, 'top_articles': top_articles}
    return render(request, 'search_results.html', context)

Pi_network_Market_Niger/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Mon marché en ligne{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <!-- Bibliothèques en lien CDN -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" integrity="sha512-+z0hwmRt1Lz+GYdJGy0yo73xH2gh7f4q3uYdYemqe7VwLGOiNR92ZTjKs90QXB7odOefxh+d0ymVYzDdKf68A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    {% block extra_head %}{% endblock %}
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="/">Marché de Niamey</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'search' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'shop:shop_list' %}">Aller au Marché</a>
                </li>
                {% if user.is_authenticated %}
                {% with cart_items=request.user.cart.cartitem_set.all %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'panier:cart_detail' %}">
                        <i class="fa fa-shopping-cart"></i> Mon panier
                        <span class="badge badge-pill badge-info">{{ cart_items.count }}</span>
                        </a>
                    </li>
                {% endwith %}

                {% endif %}

                {% load static %}

                {% if user.is_authenticated %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            {{user.username}} <img src="{% if user.avatar %}{{ user.avatar.url }}{% else %}{% static 'user/images/avatar.jpg' %}{% endif %}" alt="Avatar" class="rounded-circle" height="30" width="30">
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            {% if user.fonction == 2 %}
                                <a class="dropdown-item" href="{% url 'commande:dashboard' %}">Tableau de bord Vendeur</a>
                                <a class="dropdown-item" href="{% url 'shop:vendor_dashboard' %}">Gérer la boutique</a>
                            {% elif user.fonction == 3 %}
                                <a class="dropdown-item" href="#">Tableau de bord Client</a>
                                <a class="dropdown-item" href="{% url 'commande:order_history' %}">Mes Commandes</a>
                            {% elif user.fonction == 4 %}
                                <a class="dropdown-item" href="#">Tableau de bord Livreur</a>
                            {% endif %}
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="#">Modifier le profil</a>
                            <a class="dropdown-item" href="{% url 'user:logout' %}">Déconnexion</a>
                        </div>
                        
                    </li>
                {% endif %}


              </ul>
              
            <ul class="navbar-nav">
                {% if user.is_authenticated %}
                
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'user:register' %}">Inscription</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'user:login' %}">Connexion</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </nav>
    <div class="container my-5" >
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }}">
                    {{ message }}
                </div>
            {% endfor %}
        {% endif %}

        {% block content %}{% endblock %}
    </div>
</body>
</html>

Pi_network_Market_Niger/templates/search_results.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<div style="background-image: url('../static/images/marcher_Niamey.png'); background-repeat: no-repeat; background-position: center top; background-size: contain; padding-top: 150px;">
        {% if request.GET.q %}
            <h1>Résultats de recherche pour "{{ request.GET.q }}"</h1>
        {% endif %}
        <form method="get">
            <div class="form-group">
                <div class="input-group">
                    <input type="text" class="form-control" name="q" placeholder="Rechercher un article" value="{{ request.GET.q }}">
                    <div class="input-group-append">
                        <button type="submit" class="btn btn-primary"><i class="fa fa-search"></i> Rechercher</button>
                    </div>
                </div>
            </div>
        </form>
        {% if not request.GET.q and popular_articles %}
            <h2>Articles les plus consultés :</h2>
            <ul class="list-group">
                {% for article in popular_articles %}
                    <li class="list-group-item">{{ article.name }} - {{ article.price }} €</li>
                {% endfor %}
            </ul>
        {% endif %}
        {% if request.GET.q %}
            {% if articles %}
                <ul class="list-group">
                    {% for article in articles %}
                        <li class="list-group-item">
                            <div class="row">
                                <div class="col-md-2">
                                    {% comment %} <img src="{{ article.image.url }}" class="img-fluid" style="max-height: 90px";> {% endcomment %}
                                    {% if article.image %}
                                        <img src="{{ article.image.url }}" class="img-fluid" style="max-height: 90px";>
                                    {% else %}
                                        <img src="{% static 'images/default-store.jpg' %}" class="img-fluid" style="max-height: 90px";>
                                    {% endif %}
                                </div>
                                <div class="col-md-10">
                                    <p>
                                        
                                        <a href="{% url 'shop:article_detail' article_id=article.id %}">{{ article.name }} - {{ article.price }} FCFA   </a>  --- Vendeur : <a href="{{ article.get_absolute_url }}">{{ article.vendeur }}</a>
                                    </p>
                                </div>
                            </div>
                        </li>
                    {% endfor %}
                </ul>
                {% if articles.has_other_pages %}
                    <nav>
                        <ul class="pagination justify-content-center mt-4">
                            {% if articles.has_previous %}
                                <li class="page-item"><a href="?q={{ request.GET.q }}&page={{ articles.previous_page_number }}" class="page-link">&laquo;</a></li>
                            {% else %}
                                <li class="page-item disabled"><a class="page-link">&laquo;</a></li>
                            {% endif %}

                            {% for i in articles.paginator.page_range %}
                                {% if articles.number == i %}
                                    <li class="page-item active"><a class="page-link">{{ i }}</a></li>
                                {% elif i > articles.number|add:'-3' and i < articles.number|add:'3' %}
                                    <li class="page-item"><a href="?q={{ request.GET.q }}&page={{ i }}" class="page-link">{{ i }}</a></li>
                                {% endif %}
                            {% endfor %}

                            {% if articles.has_next %}
                                <li class="page-item"><a href="?q={{ request.GET.q }}&page={{ articles.next_page_number }}" class="page-link">&raquo;</a></li>
                            {% else %}
                                <li class="page-item disabled"><a class="page-link">&raquo;</a></li>
                            {% endif %}
                        </ul>
                    </nav>
                {% endif %}

            {% else %}
                <p>Aucun article trouvé.</p>
            {% endif %}
        {% endif %}
    </div>
{% endblock %}